# .github/workflows/main.yml
name: 'Run Power Outage Scraper'

# این بخش مهم‌ترین قسمت است:
# به گیت‌هاب اجازه می‌دهد این اکشن را به صورت دستی اجرا کنید
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. کد شما را از ریپازیتوری دریافت می‌کند
      - name: Check out repository code
        uses: actions/checkout@v3

      # 2. پایتون را نصب و راه‌اندازی می‌کند
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. کتابخانه‌های مورد نیاز را نصب می‌کند
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. اسکریپت اصلی را اجرا می‌کند
      - name: Run scraper script
        run: python scraper.py
